/* eslint-disable max-lines */
import { IMusic } from '@/interfaces/music';

export const dataMusic: IMusic[] = [
  {
    author: 'Regina Spektor',
    title: 'Us',
    id: 'fczPlmz-Vug',
    ano: 2003,
  },
  {
    author: 'Cheiro de Amor/Carla Visi',
    title: 'Vai Sacudir, Vai Abalar',
    id: 'bEjaM9GbI6s',
    ano: 1996,
  },
  {
    author: 'Regina Spektor',
    title: "Don't Leave Me (Ne Me Quitte Pas)",
    id: 'BWXWivwhi14',
    ano: 2012,
  },
  {
    author: 'Banda Eva/Ivete Sangalo',
    title: 'Beleza Rara',
    id: 'I1cJnN-o7vU',
    ano: 1996,
  },
  {
    author: 'Thaeme e Thiago',
    title: 'Cafajeste',
    id: '4GnnRiezYd8',
    ano: 2014,
  },
  {
    author: 'Babado Novo',
    title: 'Babado Novo - Bola De Sabão',
    id: '_w3AoEcImkw',
    ano: 2005,
  },
  {
    author: 'Roxette',
    title: 'It Must Have Been Love',
    id: 'k2C5TjS2sh4',
    ano: 1986,
  },
  {
    author: 'Vivo',
    title: '"DELEI" – O rapaz que vive atrasado',
    id: '3QaxlK4kolw',
    ano: 2014,
  },
  {
    author: 'Gaby Amarantos',
    title: 'Ex Mai Love',
    id: 's-5RfIXRIto',
    ano: 2012,
  },
  {
    author: 'Psirico',
    title: 'Psirico - Lepo Lepo (Clipe Oficial)',
    id: 'AHVS5DW434g',
    ano: 2014,
  },
  {
    author: 'Banda Vingadora',
    title: 'Banda Vingadora - Metralhadora [Clipe Oficial]',
    id: 'YzCoZGsod0c',
    ano: 2015,
  },
  {
    author: 'Malu',
    title: 'Disco Arranhado (Funk Remix)',
    id: 'kykoK_afoAQ',
    ano: 2021,
  },
  {
    author: 'Paula Fernandes',
    title: 'Taylor Swift, Paula Fernandes - Long Live (Official Music Video)',
    id: '1etzkcAo6WA',
    ano: 2010,
  },
  {
    author: 'Luis Fonsi',
    title: 'Luis Fonsi - Despacito ft. Daddy Yankee',
    id: 'kJQP7kiw5Fk',
    ano: 2017,
  },
  {
    author: 'Shakira',
    title: 'Shakira - Rabiosa (English Version) ft. Pitbull',
    id: 'a5irTX82olg',
    ano: 2010,
  },
  {
    author: 'Naiara Azevedo',
    title: 'Naiara Azevedo COITADO (Clipe Oficial DVD HD)',
    id: 'cus-lGN0vds',
    ano: 2016,
  },
  {
    author: 'Miley Cyrus',
    title: 'Miley Cyrus - Party In The U.S.A. (Official Video)',
    id: 'M11SvDtPBhA',
    ano: 2009,
  },
  {
    author: 'Vengaboys',
    title: 'Vengaboys - We like to Party! (The Vengabus)',
    id: '6Zbi0XmGtMw',
    ano: 1998,
  },
  {
    author: 'Giulia Be',
    title: 'Giulia Be - menina solta (video)',
    id: 'vz9XHsctOtc',
    ano: 2020,
  },
  {
    author: 'Caroline Jones',
    title: 'Caroline Jones - Rise (Official Music Video)',
    id: 'VqlwKBrrMXk',
    ano: 2017,
  },
  {
    author: 'Kelly Key',
    title: 'Kelly Key - Cachorrinho (Clipe Oficial)',
    id: 'bANQVGy-wq4',
    ano: 2001,
  },
  {
    author: 'Spice Girls',
    title: 'Spice Girls - Wannabe',
    id: 'gJLIiF15wjQ',
    ano: 1996,
  },
  {
    author: 'Aqua',
    title: 'Aqua - Barbie Girl (Official Music Video)',
    id: 'ZyhrYis509A',
    ano: 1997,
  },
  {
    author: 'Loona',
    title: 'Loona - Parapapapapa',
    id: 'Q_NqQq51jaM',
    ano: 2009,
  },
  {
    author: 'Vengaboys',
    title: 'Vengaboys - Boom Boom Boom (Live in Germany 2012 HD)',
    id: 'YKNkC6Sk7DU',
    ano: 1998,
  },
  {
    author: 'Carly Rae Jepsen',
    title: 'Carly Rae Jepsen - Call Me Maybe',
    id: 'fWNaR-rxAic',
    ano: 2012,
  },
  {
    author: 'Imagine Dragons',
    title: 'Imagine Dragons - Radioactive',
    id: 'ktvTqknDobU',
    ano: 2012,
  },
  {
    author: 'Rednex',
    title: 'Rednex - Cotton Eye Joe (Official Music Video) [HD] - RednexMusic com',
    id: 'mOYZaiDZ7BM',
    ano: 1995,
  },
  {
    author: 'Boom',
    title: 'Boom! - How Do You Do (C. Baumann Video Edit)',
    id: '23UGN3qqBWY',
    ano: 2009,
  },
  {
    author: 'Loretta Lynn, Conway Twitty',
    title: 'Conway Twitty Loretta Lynn Louisiana Woman , Mississippi Man',
    id: '2Gd0tgGVPB0',
    ano: 1973,
  },
  {
    author: 'Avicii',
    title: 'Avicii - Hey Brother',
    id: '6Cp6mKbRTQY',
    ano: 2013,
  },
  {
    author: 'OneRepublic',
    title: 'OneRepublic - Counting Stars (Official Music Video)',
    id: 'hT_nvWreIhg',
    ano: 2013,
  },
  {
    author: 'David Guetta',
    title: 'David Guetta - Titanium ft. Sia (Official Video)',
    id: 'JRfuAukYTKg',
    ano: 2011,
  },
  {
    author: 'Ricky Martin',
    title: 'Ricky Martin - Livin La Vida Loca',
    id: 'p47fEXGabaY',
    ano: 1999,
  },
  {
    author: 'Las Ketchup',
    title: 'Aserejé (The Ketchup Song) [Spanish Version] - Las Ketchup',
    id: 'arZZw8NyPq8',
    ano: 2002,
  },
  {
    author: 'P!nk',
    title: 'P!nk - Try (Official Video)',
    id: 'yTCDVfMz15M',
    ano: 2012,
  },
  {
    author: 'Latino',
    title: 'Latino - Renata',
    id: 'LnAJjRflHFE',
    ano: 2004,
  },
  {
    author: 'Perlla',
    title: 'Tremendo Vacilao',
    id: 'DN5_iOrJjfc',
    ano: 2006,
  },
  {
    author: 'Anastacia',
    title: 'Anastacia - Sick and Tired (from Live at Last)',
    id: 'CshDagHHzmI',
    ano: 2017,
  },
  {
    author: 'Anne Marie',
    title: 'Anne Marie - Ciao Adios (Radio 1s Big Weekend 2017)',
    id: 'FrA98gZGbDI',
    ano: 2016,
  },
  {
    author: 'Luka',
    title: 'Luka - Tô nem aí (Clipe)',
    id: 'vO8XQD6mHNg',
    ano: 2003,
  },
  {
    author: 'Charli XCX',
    title: 'Charli XCX - Break The Rules [Official Video]',
    id: 'ABhDiXbUaBE',
    ano: 2014,
  },
  {
    author: 'Marcelo D2',
    title: 'Marcelo D2 & Claudia - Desabafar / Deixa Eu Dizer [Fast Five Soundtrack] w Lyrics',
    id: 'fTGIHRT9KsI',
    ano: 2008,
  },
  {
    author: 'Shania Twain',
    title: 'Shania Twain - Any Man Of Mine (Official Music Video)',
    id: '8N2k-gv6xNE',
    ano: 1995,
  },
  {
    author: 'Ananda',
    title: 'Ananda, Joker Beats - Quero Que Tu Vá',
    id: 'w_ejwSACf_U',
    ano: 2019,
  },
  {
    author: 'Jessie J',
    title: 'Jessie J - Price Tag ft. B.o.B',
    id: 'qMxX-QOV9tI',
    ano: 2011,
  },
  {
    author: 'Sean Kingston',
    title: 'Sean Kingston - Beautiful Girls',
    id: 'MrTz5xjmso4',
    ano: 2009,
  },
  {
    author: 'Joan Osborne',
    title: 'Joan Osborne - One Of Us',
    id: 'aDdOnl0bHO4',
    ano: 1995,
  },
  {
    author: 'Amy Winehouse',
    title: 'Amy Winehouse - Rehab',
    id: 'KUmZp8pR1uc',
    ano: 2006,
  },
  {
    author: 'Amy Winehouse',
    title: 'Amy Winehouse - Back To Black',
    id: 'TJAfLE39ZZ8',
    ano: 2006,
  },
  {
    author: 'Avril Lavigne',
    title: 'Avril Lavigne - Complicated (Official Video)',
    id: '5NPBIwQyPWE',
    ano: 2002,
  },
  {
    author: 'Maroon 5',
    title: 'Maroon 5 - Sugar (Official Music Video)',
    id: '09R8_2nJtjg',
    ano: 2015,
  },
  {
    author: 'Camila Cabello',
    title: 'Camila Cabello - Havana Official Music Video',
    id: 'I3vks3Nblhw',
    ano: 2018,
  },
  {
    author: 'Twenty One Pilots',
    title: 'twenty one pilots - Ride (Official Video)',
    id: 'Pw-0pbY9JeU',
    ano: 2015,
  },
  {
    author: 'Loona',
    title: 'Loona - Vamos a la playa OFFICIAL VIDEO',
    id: 'X-77txuiVXs',
    ano: 2010,
  },
  {
    author: 'Cherona',
    title: 'Cherona - Rigga-Ding-Dong-Song (Videoclip)',
    id: '3f43xmRqxOM',
    ano: 2009,
  },
  {
    author: 'Aqua',
    title: 'Aqua - Cartoon Heroes',
    id: 'Q_LPJllaogU',
    ano: 2003,
  },
  {
    author: 'Red Hot Chili Peppers',
    title: 'Red Hot Chili Peppers - Californication [Official Music Video]',
    id: 'YlUKcNNmywk',
    ano: 1999,
  },
  {
    author: 'Thaeme & Thiago',
    title: 'Thaeme & Thiago - Ai que Dó',
    id: 'Ul4fQt4VvoA',
    ano: 2012,
  },
  {
    author: 'Kesha',
    title: 'Ke$ha - Take It Off',
    id: 'edP0L6LQzZE',
    ano: 2010,
  },
  {
    author: 'Empreguetes',
    title: 'Vida De Empreguete',
    id: 'LuNexytb77g',
    ano: 2012,
  },
  {
    author: 'Jameika Mansur',
    title: 'Clima de Rodeio',
    id: '8rGgsN5RAmI',
    ano: 2003,
  },
  {
    author: 'Miranda Cosgrove',
    title: 'About You Now (Video)',
    id: 'AlIUNtQEI_s',
    ano: 2008,
  },
  {
    author: 'Miranda Cosgrove',
    title: 'Leave It All To Me',
    id: 'HPM05dQgdig',
    ano: 2008,
  },
  {
    author: 'Lily Allen',
    title: 'Not Fair',
    id: 'fUYaosyR4bE',
    ano: 2009,
  },
  {
    author: 'Roberta Campos',
    title: 'De Janeiro A Janeiro',
    id: 'J08WH4-4798',
    ano: 2008,
  },
];
