/* eslint-disable max-lines */
import { IMusic } from '@/interfaces/music';

export enum CategoryEnum {
  'reload' = 'reload',
  'available' = 'available',
}

export const dataMusic: IMusic[] = [
  {
    author: 'Regina Spektor',
    title: 'Us',
    id: 'fczPlmz-Vug',
    year: 2003,
    category: CategoryEnum.reload,
    views: '17M',
    likes: '103k',
    comments: '5k',
    durationInSeconds: 4.02,
  },
  {
    author: 'Cheiro de Amor/Carla Visi',
    title: 'Vai Sacudir, Vai Abalar',
    id: 'bEjaM9GbI6s',
    year: 1996,
    category: CategoryEnum.reload,
    views: '3.8M',
    likes: '38k',
    comments: '1.6k',
    durationInSeconds: 3.58,
  },
  {
    author: 'Regina Spektor',
    title: "Don't Leave Me (Ne Me Quitte Pas)",
    id: 'BWXWivwhi14',
    year: 2012,
    category: CategoryEnum.reload,
    views: '7.2M',
    likes: '62k',
    comments: '3.3k',
    durationInSeconds: 3.43,
  },
  {
    author: 'Banda Eva/Ivete Sangalo',
    title: 'Beleza Rara',
    id: 'I1cJnN-o7vU',
    year: 1996,
    category: CategoryEnum.reload,
    views: '8.3M',
    likes: '49k',
    comments: '1.9k',
    durationInSeconds: 4,
  },
  {
    author: 'Thaeme e Thiago',
    title: 'Cafajeste',
    id: '4GnnRiezYd8',
    year: 2014,
    category: CategoryEnum.reload,
    views: '31M',
    likes: '149k',
    comments: '3.6k',
    durationInSeconds: 2.54,
  },
  {
    author: 'Babado Novo',
    title: 'Babado Novo - Bola De Sabão',
    id: '_w3AoEcImkw',
    year: 2005,
    category: CategoryEnum.reload,
    comments: '1.4k',
    durationInSeconds: 3.8,
    views: '3.7M',
    likes: '30k',
  },
  {
    author: 'Roxette',
    title: 'It Must Have Been Love',
    id: 'k2C5TjS2sh4',
    year: 1986,
    category: CategoryEnum.reload,
    comments: '86k',
    durationInSeconds: 4.15,
    views: '641M',
    likes: '2.5M',
  },
  {
    author: 'Vivo',
    title: '"DELEI" - O rapaz que vive atrasado',
    id: '3QaxlK4kolw',
    year: 2014,
    category: CategoryEnum.reload,
    comments: '217',
    durationInSeconds: 2.3,
    views: '113k',
    likes: '1.9k',
  },
  {
    author: 'Gaby Amarantos',
    title: 'Ex Mai Love',
    id: 's-5RfIXRIto',
    year: 2012,
    category: CategoryEnum.reload,
    views: '805k',
    likes: '18k',
    comments: '690',
    durationInSeconds: 2.53,
  },
  {
    author: 'Psirico',
    title: 'Psirico - Lepo Lepo (Clipe Oficial)',
    id: 'AHVS5DW434g',
    year: 2014,
    category: CategoryEnum.reload,
    views: '122M',
    likes: '660k',
    comments: '26k',
    durationInSeconds: 2.39,
  },
  {
    author: 'Banda Vingadora',
    title: 'Banda Vingadora - Metralhadora [Clipe Oficial]',
    id: 'YzCoZGsod0c',
    year: 2015,
    category: CategoryEnum.reload,
    views: '351M',
    likes: '2.5M',
    comments: '115k',
    durationInSeconds: 2.57,
  },
  {
    author: 'Malu e LUCAS',
    title: 'DISCO ARRANHADO (FUNK REMIX) MALU & DJ LUCAS BEAT',
    id: 'JisUmQmEqB8',
    year: 2021,
    category: CategoryEnum.reload,
    views: '20M',
    likes: '249k',
    comments: '5k',
    durationInSeconds: 2.04,
  },
  {
    author: 'Paula Fernandes',
    title: 'Taylor Swift, Paula Fernandes - Long Live (Official Music Video)',
    id: '1etzkcAo6WA',
    year: 2010,
    category: CategoryEnum.available,
    views: '24M',
    likes: '260k',
    comments: '14.7k',
    durationInSeconds: 5.18,
  },
  {
    author: 'Luis Fonsi',
    title: 'Luis Fonsi - Despacito ft. Daddy Yankee',
    id: 'kJQP7kiw5Fk',
    year: 2017,
    category: CategoryEnum.reload,
    views: '8b',
    likes: '50m',
    comments: '4.2M',
    durationInSeconds: 4.41,
  },
  {
    author: 'Shakira',
    title: 'Shakira - Rabiosa (English Version) ft. Pitbull',
    id: 'a5irTX82olg',
    year: 2010,
    category: CategoryEnum.reload,
    views: '272M',
    likes: '790k',
    comments: '180k',
    durationInSeconds: 2.5,
  },
  {
    author: 'Naiara Azevedo',
    title: 'Naiara Azevedo COITADO (Clipe Oficial DVD HD)',
    id: 'cus-lGN0vds',
    year: 2016,
    category: CategoryEnum.reload,
    views: '13M',
    likes: '110k',
    comments: '1.9k',
    durationInSeconds: 3.54,
  },
  {
    author: 'Miley Cyrus',
    title: 'Miley Cyrus - Party In The U.S.A. (Official Video)',
    id: 'M11SvDtPBhA',
    year: 2009,
    category: CategoryEnum.reload,
    views: '895M',
    likes: '4M',
    comments: '400k',
    durationInSeconds: 3.27,
  },
  {
    author: 'Vengaboys',
    title: 'Vengaboys - We like to Party! (The Vengabus)',
    id: '6Zbi0XmGtMw',
    year: 1998,
    category: CategoryEnum.reload,
    views: '170M',
    likes: '1.1M',
    comments: '39k',
    durationInSeconds: 3.44,
  },
  {
    author: 'Giulia Be',
    title: 'Giulia Be - menina solta (video)',
    id: 'vz9XHsctOtc',
    year: 2020,
    category: CategoryEnum.available,
    views: '209M',
    likes: '2.2M',
    comments: '45k',
    durationInSeconds: 2.48,
  },
  {
    author: 'Caroline Jones',
    title: 'Caroline Jones - Rise (Official Music Video)',
    id: 'VqlwKBrrMXk',
    year: 2017,
    category: CategoryEnum.reload,
    views: '6.4M',
    likes: '83k',
    comments: '1.9k',
    durationInSeconds: 3.2,
  },
  {
    author: 'Kelly Key',
    title: 'Kelly Key - Cachorrinho (Clipe Oficial)',
    id: 'bANQVGy-wq4',
    year: 2001,
    category: CategoryEnum.reload,
    views: '2.5M',
    likes: '52k',
    comments: '1.7k',
    durationInSeconds: 3.54,
  },
  {
    author: 'Spice Girls',
    title: 'Spice Girls - Wannabe',
    id: 'gJLIiF15wjQ',
    year: 1996,
    category: CategoryEnum.reload,
    views: '590M',
    likes: '4M',
    comments: '128k',
    durationInSeconds: 3.55,
  },
  {
    author: 'Aqua',
    title: 'Aqua - Barbie Girl (Official Music Video)',
    id: 'ZyhrYis509A',
    year: 1997,
    category: CategoryEnum.reload,
    views: '1.1b',
    likes: '6.8k',
    comments: '370k',
    durationInSeconds: 3.21,
  },
  {
    author: 'Loona',
    title: 'Loona - Parapapapapa',
    id: 'Q_NqQq51jaM',
    year: 2009,
    category: CategoryEnum.reload,
    views: '17M',
    likes: '44k',
    comments: '1.6k',
    durationInSeconds: 3.4,
  },
  {
    author: 'Vengaboys',
    title: 'Vengaboys - Boom Boom Boom (Live in Germany 2012 HD)',
    id: 'YKNkC6Sk7DU',
    year: 1998,
    category: CategoryEnum.available,
    views: '3.2M',
    likes: '14k',
    comments: '318',
    durationInSeconds: 1.59,
  },
  {
    author: 'Carly Rae Jepsen',
    title: 'Carly Rae Jepsen - Call Me Maybe',
    id: 'fWNaR-rxAic',
    year: 2012,
    category: CategoryEnum.reload,
    views: '1.4b',
    likes: '8.4M',
    comments: '630k',
    durationInSeconds: 3.19,
  },
  {
    author: 'Imagine Dragons',
    title: 'Imagine Dragons - Radioactive',
    id: 'ktvTqknDobU',
    year: 2012,
    category: CategoryEnum.reload,
    views: '1.4b',
    likes: '9.1M',
    comments: '340k',
    durationInSeconds: 4.21,
  },
  {
    author: 'Rednex',
    title: 'Rednex - Cotton Eye Joe (Official Music Video) [HD] - RednexMusic com',
    id: 'mOYZaiDZ7BM',
    year: 1995,
    category: CategoryEnum.reload,
    views: '195M',
    likes: '1.3M',
    comments: '51k',
    durationInSeconds: 3.14,
  },
  {
    author: 'Boom',
    title: 'Boom! - How Do You Do (C. Baumann Video Edit)',
    id: '23UGN3qqBWY',
    year: 2009,
    category: CategoryEnum.reload,
    views: '10M',
    likes: '60k',
    comments: '1.8k',
    durationInSeconds: 3.34,
  },
  {
    author: 'Loretta Lynn, Conway Twitty',
    title: 'Conway Twitty Loretta Lynn Louisiana Woman , Mississippi Man',
    id: '2Gd0tgGVPB0',
    year: 1973,
    category: CategoryEnum.available,
    views: '430k',
    likes: '8.8k',
    comments: '830',
    durationInSeconds: 2.13,
  },
  {
    author: 'Avicii',
    title: 'Avicii - Hey Brother',
    id: '6Cp6mKbRTQY',
    year: 2013,
    category: CategoryEnum.reload,
    views: '279M',
    likes: '2.6M',
    comments: '105k',
    durationInSeconds: 4.23,
  },
  {
    author: 'OneRepublic',
    title: 'OneRepublic - Counting Stars (Official Music Video)',
    id: 'hT_nvWreIhg',
    year: 2013,
    category: CategoryEnum.reload,
    views: '3.6b',
    likes: '16M',
    comments: '470k',
    durationInSeconds: 4.43,
  },
  {
    author: 'David Guetta',
    title: 'David Guetta - Titanium ft. Sia (Official Video)',
    id: 'JRfuAukYTKg',
    year: 2011,
    category: CategoryEnum.reload,
    views: '1.6b',
    likes: '8.2M',
    comments: '296k',
    durationInSeconds: 4.05,
  },
  {
    author: 'Ricky Martin',
    title: 'Ricky Martin - Livin La Vida Loca',
    id: 'p47fEXGabaY',
    year: 1999,
    category: CategoryEnum.reload,
    views: '438M',
    likes: '2M',
    comments: '65k',
    durationInSeconds: 3.42,
  },
  {
    author: 'Las Ketchup',
    title: 'Aserejé (The Ketchup Song) [Spanish Version] - Las Ketchup',
    id: 'arZZw8NyPq8',
    year: 2002,
    category: CategoryEnum.reload,
    views: '261M',
    likes: '1.8M',
    comments: '52k',
    durationInSeconds: 3.3,
  },
  {
    author: 'P!nk',
    title: 'P!nk - Try (Official Video)',
    id: 'yTCDVfMz15M',
    year: 2012,
    category: CategoryEnum.reload,
    views: '529M',
    likes: '2.5M',
    comments: '78k',
    durationInSeconds: 4.09,
  },
  {
    author: 'Latino',
    title: 'Latino - Renata',
    id: 'LnAJjRflHFE',
    year: 2004,
    category: CategoryEnum.reload,
    views: '8.8M',
    likes: '69k',
    comments: '2.3k',
    durationInSeconds: 3.29,
  },
  {
    author: 'Perlla',
    title: 'Tremendo Vacilao',
    id: 'DN5_iOrJjfc',
    year: 2006,
    category: CategoryEnum.reload,
    views: '9M',
    likes: '118k',
    comments: '0',
    durationInSeconds: 3.44,
  },
  {
    author: 'Anastacia',
    title: 'Anastacia - Sick and Tired (from Live at Last)',
    id: 'CshDagHHzmI',
    year: 2017,
    category: CategoryEnum.reload,
    views: '33M',
    likes: '129k',
    comments: '2.5k',
    durationInSeconds: 3.33,
  },
  {
    author: 'Anne Marie',
    title: 'Anne Marie - Ciao Adios (Radio 1s Big Weekend 2017)',
    id: 'FrA98gZGbDI',
    year: 2016,
    category: CategoryEnum.reload,
    views: '31M',
    likes: '250k',
    comments: '4.2k',
    durationInSeconds: 3.42,
  },
  {
    author: 'Luka',
    title: 'Luka - Tô nem aí (Clipe)',
    id: 'vO8XQD6mHNg',
    year: 2003,
    category: CategoryEnum.reload,
    views: '2.7M',
    likes: '50k',
    comments: '2.1k',
    durationInSeconds: 2.32,
  },
  {
    author: 'Charli XCX',
    title: 'Charli XCX - Break The Rules [Official Video]',
    id: 'ABhDiXbUaBE',
    year: 2014,
    category: CategoryEnum.reload,
    views: '187M',
    likes: '1.6M',
    comments: '50k',
    durationInSeconds: 3.25,
  },
  {
    author: 'Marcelo D2',
    title: 'Marcelo D2 & Claudia - Desabafar / Deixa Eu Dizer [Fast Five Soundtrack] w Lyrics',
    id: 'fTGIHRT9KsI',
    year: 2008,
    category: CategoryEnum.reload,
    views: '5.5M',
    likes: '100k',
    comments: '1.5k',
    durationInSeconds: 2.55,
  },
  {
    author: 'Shania Twain',
    title: 'Shania Twain - Any Man Of Mine (Official Music Video)',
    id: '8N2k-gv6xNE',
    year: 1995,
    category: CategoryEnum.reload,
    views: '166M',
    likes: '766k',
    comments: '19k',
    durationInSeconds: 4.12,
  },
  {
    author: 'Ananda',
    title: 'Ananda, Joker Beats - Quero Que Tu Vá',
    id: 'w_ejwSACf_U',
    year: 2019,
    category: CategoryEnum.reload,
    views: '87M',
    likes: '1.8M',
    comments: '79k',
    durationInSeconds: 2.2,
  },
  {
    author: 'Jessie J',
    title: 'Jessie J - Price Tag ft. B.o.B',
    id: 'qMxX-QOV9tI',
    year: 2011,
    category: CategoryEnum.reload,
    views: '818M',
    likes: '4M',
    comments: '200k',
    durationInSeconds: 4,
  },
  {
    author: 'Sean Kingston',
    title: 'Sean Kingston - Beautiful Girls',
    id: 'MrTz5xjmso4',
    year: 2009,
    category: CategoryEnum.reload,
    views: '1b',
    likes: '8.4M',
    comments: '246k',
    durationInSeconds: 4.21,
  },
  {
    author: 'Joan Osborne',
    title: 'Joan Osborne - One Of Us',
    id: 'aDdOnl0bHO4',
    year: 1995,
    category: CategoryEnum.reload,
    views: '39M',
    likes: '439k',
    comments: '10k',
    durationInSeconds: 4.5,
  },
  {
    author: 'Amy Winehouse',
    title: 'Amy Winehouse - Rehab',
    id: 'KUmZp8pR1uc',
    year: 2006,
    category: CategoryEnum.reload,
    views: '310M',
    likes: '1.8M',
    comments: '85k',
    durationInSeconds: 3.33,
  },
  {
    author: 'Amy Winehouse',
    title: 'Amy Winehouse - Back To Black',
    id: 'TJAfLE39ZZ8',
    year: 2006,
    category: CategoryEnum.reload,
    views: '850M',
    likes: '4.6M',
    comments: '120k',
    durationInSeconds: 4,
  },
  {
    author: 'Avril Lavigne',
    title: 'Avril Lavigne - Complicated (Official Video)',
    id: '5NPBIwQyPWE',
    year: 2002,
    category: CategoryEnum.reload,
    views: '550M',
    likes: '3.8M',
    comments: '140k',
    durationInSeconds: 3.13,
  },
  {
    author: 'Maroon 5',
    title: 'Maroon 5 - Sugar (Official Music Video)',
    id: '09R8_2nJtjg',
    year: 2015,
    category: CategoryEnum.reload,
    views: '3.7b',
    likes: '15M',
    comments: '514k',
    durationInSeconds: 5,
  },
  {
    author: 'Camila Cabello',
    title: 'Camila Cabello - Havana (Audio) ft. Young Thug',
    id: 'HCjNJDNzw8Y',
    year: 2018,
    category: CategoryEnum.reload,
    views: '1.9b',
    likes: '10M',
    comments: '430k',
    durationInSeconds: 3.38,
  },
  {
    author: 'Twenty One Pilots',
    title: 'twenty one pilots - Ride (Official Video)',
    id: 'Pw-0pbY9JeU',
    year: 2015,
    category: CategoryEnum.reload,
    views: '1.3b',
    likes: '10k',
    comments: '312k',
    durationInSeconds: 3.45,
  },
  {
    author: 'Loona',
    title: 'Loona - Vamos a la playa OFFICIAL VIDEO',
    id: 'X-77txuiVXs',
    year: 2010,
    category: CategoryEnum.reload,
    views: '142M',
    likes: '670k',
    comments: '34k',
    durationInSeconds: 2.57,
  },
  {
    author: 'Cherona',
    title: 'Cherona - Rigga-Ding-Dong-Song (Videoclip)',
    id: '3f43xmRqxOM',
    year: 2009,
    category: CategoryEnum.reload,
    views: '12M',
    likes: '66k',
    comments: '990',
    durationInSeconds: 0,
  },
  {
    author: 'Aqua',
    title: 'Aqua - Cartoon Heroes',
    id: 'Q_LPJllaogU',
    year: 2003,
    category: CategoryEnum.reload,
    views: '25M',
    likes: '119k',
    comments: '8.7k',
    durationInSeconds: 4.19,
  },
  {
    author: 'Red Hot Chili Peppers',
    title: 'Red Hot Chili Peppers - Californication [Official Music Video]',
    id: 'YlUKcNNmywk',
    year: 1999,
    category: CategoryEnum.reload,
    views: '1b',
    likes: '4.3M',
    comments: '120k',
    durationInSeconds: 5.21,
  },
  {
    author: 'Thaeme & Thiago',
    title: 'Thaeme & Thiago - Ai que Dó',
    id: 'Ul4fQt4VvoA',
    year: 2012,
    category: CategoryEnum.reload,
    views: '19M',
    likes: '109k',
    comments: '1.5k',
    durationInSeconds: 3.18,
  },
  {
    author: 'Kesha',
    title: 'Ke$ha - Take It Off',
    id: 'edP0L6LQzZE',
    year: 2010,
    category: CategoryEnum.reload,
    views: '149M',
    likes: '1.3M',
    comments: '63k',
    durationInSeconds: 3.42,
  },
  {
    author: 'Empreguetes',
    title: 'Vida De Empreguete',
    id: 'LuNexytb77g',
    year: 2012,
    category: CategoryEnum.reload,
    views: '10M',
    likes: '200k',
    comments: '2.1k',
    durationInSeconds: 2.57,
  },
  {
    author: 'Jameika Mansur',
    title: 'Clima de Rodeio',
    id: '8rGgsN5RAmI',
    year: 2003,
    category: CategoryEnum.reload,
    views: '5.7M',
    likes: '65k',
    comments: '0',
    durationInSeconds: 3.5,
  },
  {
    author: 'Miranda Cosgrove',
    title: 'About You Now (Video)',
    id: 'AlIUNtQEI_s',
    year: 2008,
    category: CategoryEnum.reload,
    views: '34M',
    likes: '312k',
    comments: '25.7k',
    durationInSeconds: 3.12,
  },
  {
    author: 'Miranda Cosgrove',
    title: 'Leave It All To Me',
    id: 'HPM05dQgdig',
    year: 2008,
    category: CategoryEnum.reload,
    views: '34M',
    likes: '770k',
    comments: '58k',
    durationInSeconds: 2.46,
  },
  {
    author: 'Lily Allen',
    title: 'Not Fair',
    id: 'fUYaosyR4bE',
    year: 2009,
    category: CategoryEnum.reload,
    views: '1M',
    likes: '600k',
    comments: '29k',
    durationInSeconds: 3.5,
  },
  {
    author: 'Roberta Campos',
    title: 'De Janeiro A Janeiro',
    id: 'J08WH4-4798',
    year: 2008,
    category: CategoryEnum.reload,
    views: '35M',
    likes: '420k',
    comments: '1.4k',
    durationInSeconds: 3.1,
  },
  {
    author: 'Heart',
    title: 'Heart - "Barracuda" (1977)',
    id: 'PeMvMNpvB5M',
    year: 1977,
    category: CategoryEnum.reload,
    views: '89M',
    likes: '800k',
    comments: '30k',
    durationInSeconds: 4.24,
  },
  {
    author: 'Legião Urbana',
    title: 'Faroeste Caboclo',
    id: 'qBIxI580dI8',
    year: 1987,
    category: CategoryEnum.reload,
    views: '17M',
    likes: '170k',
    comments: '', /// ///////fix
    durationInSeconds: 9.03,
  },
  {
    author: 'Social Distortion',
    title: 'Social Distortion - Story of My Life',
    id: 'oh8zcbC_Dcw',
    year: 1990,
    category: CategoryEnum.reload,
    views: '36M',
    likes: '180k',
    comments: '8k',
    durationInSeconds: 4.45,
  },
  {
    author: 'Poison',
    title: 'Poison - Talk Dirty To Me (Official Music Video)',
    id: 'xCChxBSRo1Y',
    year: 1986,
    category: CategoryEnum.reload,
    views: '42M',
    likes: '220k',
    comments: '8.3k',
    durationInSeconds: 4.02,
  },
  {
    author: 'Journey',
    title: "Journey - Don't Stop Believin",
    id: 'VcjzHMhBtf0',
    year: 1981,
    category: CategoryEnum.reload,
    views: '181M',
    likes: '1M',
    comments: '42.4k',
    durationInSeconds: 4.11,
  },
  {
    author: 'João Bosco & Vinícius',
    title: 'Chora, Me Liga (Ao Vivo)',
    id: '6fJayNqtkM4',
    year: 2009,
    category: CategoryEnum.reload,
    views: '19M',
    likes: '168k',
    comments: '405',
    durationInSeconds: 3.01,
  },
  {
    author: 'Pat Benatar',
    title: 'Hit Me With Your Best Shot (Remastered)',
    id: 'JRD80XRMT7s',
    year: 1980,
    category: CategoryEnum.reload,
    views: '1.2M',
    likes: '21k',
    comments: '', /// //
    durationInSeconds: 2.52,
  },
  {
    author: 'Los Hermanos',
    title: 'Los Hermanos - Anna Júlia (Video Clipe)',
    id: 'umMIcZODm2k',
    year: 1999,
    category: CategoryEnum.reload,
    views: '17M',
    likes: '170k',
    comments: '6.7k',
    durationInSeconds: 3.32,
  },
  {
    author: 'Victor & Leo',
    title: 'Victor & Leo - Fada (Video) (Ao Vivo)',
    id: 'OqukL-DFYms',
    year: 2004,
    category: CategoryEnum.reload,
    views: '30M',
    likes: '166k',
    comments: '5.2k ',
    durationInSeconds: 6.02,
  },
  {
    author: 'Michel Teló',
    title: 'MICHEL TELÓ - BARÁ BERÊ [CLIPE OFICIAL]',
    id: 'gEiqSUzQ1fo',
    year: 2011,
    category: CategoryEnum.reload,
    views: '132M',
    likes: '650k',
    comments: '22.4k',
    durationInSeconds: 2.44,
  },
  {
    author: 'The Animals',
    title: 'The Animals - House of the Rising Sun',
    id: '4-43lLKaqBQ',
    year: 1964,
    category: CategoryEnum.reload,
    views: '179M',
    likes: '1.5M',
    comments: '44.5K',
    durationInSeconds: 4.08,
  },
];
