name: Check tsc and lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install dependencies and check
        run: pnpm install --frozen-lockfile
      - run: pnpm run check
      - run: pnpm run lint
