name: testing, linting and deploy

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        pnpm-version: [8.3.1]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: install dependencies
        run: pnpm i --frozen-lockfile

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: cache cypress
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}

  install_and_build:
    runs-on: ubuntu-latest
    needs: install
    timeout-minutes: 10
    strategy:
      matrix:
        pnpm-version: [8.3.1]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: install dependencies
        run: pnpm run build

      - name: cache build
        uses: actions/cache@v2
        with:
          path: build
          key: build-${{ runner.os }}

  e2e_features:
    needs: install_and_build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        pnpm-version: [8.3.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: restore build
        uses: actions/cache@v2
        with:
          path: build
          key: build-${{ runner.os }}

      - name: Cache Cypress Binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}

      - name: running e2e tests
        run: pnpm run e2e:features

  e2e_accessibility:
    needs: install_and_build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        pnpm-version: [8.3.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: restore build
        uses: actions/cache@v2
        with:
          path: build
          key: build-${{ runner.os }}

      - name: restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Cache Cypress Binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}

      - name: running e2e accessibility tests
        run: pnpm run e2e:accessibility

  unit_tests_and_up_coverage:
    needs: install
    timeout-minutes: 5
    environment: codacy_env
    runs-on: ubuntu-latest

    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    strategy:
      matrix:
        pnpm-version: [8.3.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: running tests and generate coverage
        run: pnpm run unit:coverage

      - name: up coverage to codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/lcov.info

  lint:
    needs: install
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pnpm-version: [8.3.1]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: use pnpm.js ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: check typescript
        run: pnpm run lint

  format:
    needs: install
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        pnpm-version: [8.3.1]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: use pnpm.js ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: verify if prettier is formatted
        run: pnpm run format:check

  deploy:
    environment: sentry
    timeout-minutes: 10
    needs: [unit_tests_and_up_coverage, e2e_features, e2e_accessibility, lint, format]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    strategy:
      matrix:
        node-version: [16.x]
        pnpm-version: [8.3.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: use pnpm.js ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Install dependencies and test
        run: pnpm i --frozen-lockfile

      - name: get current version
        id: get-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "::set-output name=version::$VERSION"

      - name: build App
        run: |
          echo "export const envs = { VITE_BASE_URL: '/youtube-reload', VITE_ENVIRONMENT: 'production', SENTRY_DSN: '$SENTRY_DSN', 'VERSION': '${{ steps.get-version.outputs.version }}' };" > src/core/env.ts
          pnpm run build

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/gabrielogregorio/youtube-reload.git

          echo "copy index to 404 page"
          cp build/index.html build/404.html

          npx gh-pages -d build --add -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
